notes_app/urls.py
from django.urls import path, re_path
from notes_app import views

app_name = 'notes_app'

urlpatterns =[
    path('mynotes/',views.NoteListView.as_view(),name='list_note'),
    re_path(r'^mynotes/newnote/$',views.NoteCreateView.as_view(),name='create_note'),
    re_path(r'^mynotes/(?P<pk>\d+)/$',views.NoteDetailView.as_view(),name='detail_note'),
    re_path(r'^mynotes/(?P<pk>\d+)/edit/$',views.NoteEditView.as_view(),name='note_update'),
    re_path(r'^mynotes/(?P<pk>\d+)/delete/$',views.NoteDeleteView.as_view(),name='note_delete'),
]

notesproject/urls.py
from django.contrib import admin
from django.urls import path,include
from notes_app import views

urlpatterns = [
    path('',views.index,name= 'index'),
    path('',include('notes_app.urls')),
    path('signup/',views.signup,name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('admin/', admin.site.urls),
]

notes_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Note(models.Model):
    user = models.ForeignKey(User,related_name='notes',on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("notes_app:list_note")

notes_app/forms.py
from django import forms
from .models import Note
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(widget=forms.PasswordInput())

notes_app/views.py
from django.shortcuts import render,redirect
from django.views.generic import (ListView,DetailView,DeleteView,
                                  CreateView,UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from notes_app.models import Note
from .forms import SignUpForm, LoginForm
# Create your views here.


def index(request):
    return render(request,'notes_app/index.html')


def signup(request):
    if request.user.is_authenticated:
        return redirect('notes_app:list_note')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(form.cleaned_data.get('password1'))
            user.save()
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user1 = authenticate(username=username, password=password)
            login(request,user1)
            return redirect('notes_app:list_note')
    else:
        form = SignUpForm()
    return render(request,'notes_app/signup.html',{'form':form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('index')


def user_login(request):
    if request.user.is_authenticated:
        return redirect('notes_app:list_note')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user:
                login(request,user)
                return redirect('notes_app:list_note')
    else:
        form = LoginForm()
    return render(request,'notes_app/login.html',{'form':form})


class NoteListView(LoginRequiredMixin,ListView):
    model = Note
    login_url = '/login/'
    # template_name = 'note_list.html'

    def get_queryset(self):
        return self.request.user.notes.all().order_by('-pk')


class NoteDetailView(LoginRequiredMixin,DetailView):
    model = Note
    context_object_name = 'note_details'


class NoteCreateView(LoginRequiredMixin,CreateView):
    model = Note
    # template_name = 'note_form.html'
    fields = ['text']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class NoteEditView(LoginRequiredMixin,UpdateView):
    model = Note
    fields = ['text']


class NoteDeleteView(LoginRequiredMixin,DeleteView):
    success_url = reverse_lazy('notes_app:list_note')
    model = Note
    #template_name = 'note_detail.html'

notes_app/templates/notes_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
            AnyNote
      {% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block link %}

    {% endblock %}
</head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">AnyNote</a></li>
<!--          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>-->
          {% if not user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'signup' %}">SignUp</a></li>
            <li><a class="nav-link" href="{% url 'login' %}">Login</a></li>
          {% else %}
            <li><a class="nav-link" href="{% url 'notes_app:list_note' %}">My Notes</a></li>
            <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
      <p></p>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

notes_app/templates/notes_app/note_confirm_delete.html
{% extends 'notes_app/base.html'%}
{% load static %}

{% block title %}
    AnyNote|Delete
{% endblock %}

{% block body_block %}

    <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ note.text|truncatewords:3 }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>

{% endblock %}

notes_app/templates/notes_app/note_detail.html
{% extends 'notes_app/base.html'%}
{% load static %}

{% block title %}
    AnyNote|MyNotes
{% endblock %}

{% block link %}
    <link rel="stylesheet" type="text/css" href='{% static "notes_app/stylednote.css" %}'>

{% endblock %}

{% block body_block %}
<div class="card bg-light border-info mb-3" style="box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);">
    <div class="card-header"></div>
        <div class="card-body ">
            {% filter linebreaksbr|truncatewords:40 %}
                <p class="card-text">{{ note_details.text|linebreaks }}</p>
            {% endfilter %}
<!--            <a href="{{note.id}}/" class="btn btn-primary">Details</a>-->
            <a class='btn btn-warning' href="{% url 'notes_app:note_update' pk=note_details.pk %}">Edit</a>
            <a class='btn btn-danger' href="{% url 'notes_app:note_delete' pk=note_details.pk %}">Delete</a>
        </div>
</div>
<p></p>


<!--<form method="post">-->
<!--  -->
<!--  <input type="submit" class="btn btn-danger" value="Delete">-->
<!--</form>-->
<a class='btn btn-primary' href="{% url 'notes_app:list_note'%}">My Notes</a>
{% endblock %}

notes_app/templates/notes_app/note_form.html
{% extends 'notes_app/base.html'%}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    {% if not form.instance.pk %}
        AnyNote|New Note
    {% else%}
        AnyNote|Edit Note
    {% endif %}
{% endblock %}

{% block body_block %}
<div class="card bg-light border-info" style="width: 22rem;">
    <div class="card-body">
    <h2 class="card-title">
    {% if not form.instance.pk %}
        New Note
    {% else%}
        Edit Note
    {% endif %}
    </h2>

    <form method="post" >
        {% csrf_token %}

        {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
        {% endfor %}

        {% render_field form.text placeholder='Write your note here...' class='form-control' style="resize:none;" %}
        <div class="form-group has-errors text-danger small">
            {{ form.text.errors}}
        </div>

        <input type="submit" class='btn btn-info' value="Save">
        <a class='btn btn-secondary' href="{% url 'notes_app:list_note'%}">Cancle</a>
    </form>
    </div>
</div>

{% endblock %}

notes_app/templates/notes_app/note_list.html
{% extends 'notes_app/base.html'%}
{% load static %}

{% block title %}
    AnyNote|MyNotes
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'notes_app/stylednote.css'%}">
{% endblock %}

{% block body_block %}
    <h2>Welcome {{user.username}} !</h2>
    {% if note_list %}
        <div class="card-columns">

            {% for note in note_list %}

                    <div class="card bg-light border-info mb-3" style="box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);">
                        <div class="card-header"></div>
                            <div class="card-body ">
                                    {% filter linebreaksbr|truncatewords:40 %}
                                        <p class="card-text">{{ note.text }}</p>
                                    {% endfilter %}
                                <a href="{{note.id}}/" class="btn btn-primary">Details</a>
                            </div>
                    </div>
            {% endfor %}

        </div>
    {% else %}
        <p><h2>No saved notes</h2></p>
        <p><h2>Start by adding one.</h2></p>
    {% endif %}
<!--        </div>-->

    <p></p>
    <p><a class="btn btn-success" href="{% url 'notes_app:create_note'%}">+ New Note</a></p>
{% endblock %}

templates/notes_app/Signup.html
{% extends 'notes_app/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block body_block %}
<div class="jumbotron" style="margin:auto;width:40%;margin-top:10%;">
    <form method="post" >
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
        {% endfor %}
        <div class="form-group has-errors text-danger small">
        </div>

        <div class="form-group">
            {% render_field form.username placeholder='Username' class='form-control' %}
        </div>
        <div class="form-group has-errors text-danger small">
            {{ form.username.errors}}
        </div>

        <div class="form-group">
            {% render_field form.email placeholder='Email' class='form-control'%}
        </div>
        <div class="form-group has-errors text-danger small">
            {{form.email.errors}}
        </div>

        <div class="form-group">
            {% render_field form.password1 placeholder='Password' class='form-control'%}
        </div>
        <div class="form-group has-errors text-danger small">
            {{form.password1.errors}}
        </div>

        <div class="form-group">
            {% render_field form.password2 placeholder='re-enter password' class='form-control'%}
        </div>
        <div class="form-group has-errors text-danger small">
            {{form.password2.errors}}
        </div>

         <input type="submit" class='btn btn-info' value="Signup">
    </form>
</div>

{% endblock %}

templates/notes_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
            AnyNote
      {% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block link %}

    {% endblock %}

</head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
      <div class="container">
        <ul class="navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">AnyNote</a></li>
<!--          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>-->
          {% if not user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">SignUp</a></li>
            <li><a class="nav-link" href="{% url 'login' %}">Login</a></li>
          {% else %}
            <li><a class="nav-link" href="{% url 'notes_app:list_note' %}">My Notes</a></li>
            <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
      <p></p>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/notes_app/index.html
{% extends 'notes_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    <h1>The Simplest way <br>to keep notes</h1>
    <p>Light, clean and free.</p>
    <p><a class="btn btn-success" href="{% url 'notes_app:create_note'%}">+ New Note</a></p>
</div>
{% endblock %}

templates/notes_app/login.html
{% extends 'notes_app/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block body_block %}
<div class="jumbotron" style="margin:auto;width:40%;margin-top:10%;">
    <form method="post">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <div class="form-group has-errors text-danger small">
                {{error}}
            </div>
        {% endfor %}
        <div class="form-group">
            {% render_field form.username placeholder='Username' class='form-control' %}
        </div>
        <div class="form-group has-errors text-danger small">
            {{ form.username.errors}}
        </div>
        <div class="form-group">
            {% render_field form.password placeholder='Password' class='form-control'%}
        </div>
        <div class="form-group has-errors text-danger small">
            {{form.password.errors}}
        </div>
        <input type="submit" class='btn btn-info' value="Login">
    </form>
</div>

{% endblock %}